#include "Server.h"
#define BUFF_SIZE 5000
#define SERVER_PORT 1350
#define FORWARDING_ADDR "10.238.200.107"
#define FORWARDING_PORT 1235
#define SEND_PACKET_SIZE 512
#define MAX_RX_SIZE 1316

int main (int argc, char *argv[]) {
    Forward(BUFF_SIZE, MAX_RX_SIZE, SERVER_PORT, FORWARDING_ADDR, FORWARDING_PORT, SEND_PACKET_SIZE);
}